nuxeo:
  hostname: nuxeo
  build: .
  environment:
    VIRTUAL_HOST: docker.local
    PACKAGES: "nuxeo-drive shibboleth-authentication nuxeo-diff nuxeo-virtualnavigation nuxeo-dam nuxeo-spreadsheet nuxeo-template-rendering nuxeo-web-mobile nuxeo-shibboleth-invitation nuxeo-platform-user-registration"
    PACKAGES2: "/platform/etc/data/marketplace/marketplace-CustomLoginUDL-1.0.9-SNAPSHOT.zip"
    TEMPLATES: "default,/platform/etc/data/conf/templates/shibboleth"
  # volumes:
  #   - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data:/platform/etc/data
  #   - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/CERT-CA.cer:/tmp/CERT-CA.cer:ro
  # ports:
  #   - 8080:8080
shibbolethsp:
  hostname: shib
  build: ../nuxeo-shibboleth-docker/
  environment:
    VIRTUAL_HOST: dev.local
    VIRTUAL_PROTO: https
  links:
    - nuxeo
  ports:
    - "443:443"
#   volumes:
#     - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/sp-cert.pem:/etc/shibboleth/sp-cert.pem:ro
#     - /Users/vincent/Documents/dev/java/nuxeo-udl/etc_data/sp-key.pem:/etc/shibboleth/sp-key.pem:ro
# nginx:
#   environment:
#     DEFAULT_HOST: local.dev
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - /var/run/docker.sock:/tmp/docker.sock
#     - /Users/vincent/Documents/UDL/admin/wildcard_universite/:/etc/nginx/certs
#   image: jwilder/nginx-proxy
