nuxeo:
  hostname: nuxeo-pp
  domainname: ad.universite-lyon.fr
  build: .
  environment:
    VIRTUAL_HOST: docker.local
    PACKAGES: "nuxeo-drive shibboleth-authentication nuxeo-diff nuxeo-virtualnavigation nuxeo-dam nuxeo-dam-compat nuxeo-spreadsheet nuxeo-template-rendering nuxeo-web-mobile"
    TEMPLATES: "drive"
  volumes_from:
    - nuxeo_data
  ports:
    - 8080:8080
